project:
  type: website
  output-dir: docs

website:
  title: "Ethel Ogallo"
  favicon: images/favicon_io/favicon.ico   
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: activities.qmd
        text: Activities
      - href: resume2.qmd
        text: CV
    pinned: true

  page-footer: 
    center: |
      <p style="display: flex; justify-content: center; align-items: center; gap: 10px;">
        <img src="/images/EMJM.jpg" alt="EMJM+" style="height:70px;">
        <img src="/images/CDE.png" alt="CDE" style="height:80px;">
        <img src="/images/PLUS.png" alt="PLUS" style="height:80px;">
        <img src="/images/UBS.png" alt="UBS" style="height:90px;">
      </p>
      <p>Made with <a href="https://quarto.org/">Quarto</a>. Copyright 2025, Ethel Ogallo.</p>
    background: "#EEEEEE"
    
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    fontsize: 1em
    fontcolor: black
    toc: true

editor: visual

